package frontend;

import conexion.conexion;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class actualizarProveedores extends javax.swing.JFrame {

    int id;
    conexion con = new conexion();
    PreparedStatement ps;
    ResultSet rs;
    
    public actualizarProveedores() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * .- .-. - ..- .-. ---
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        areaTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        textoTelefono = new javax.swing.JLabel();
        textoID = new javax.swing.JLabel();
        areaID = new javax.swing.JTextField();
        textoNombre = new javax.swing.JLabel();
        areaNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setForeground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(null);

        cancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.setBorder(null);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar);
        cancelar.setBounds(90, 280, 160, 40);

        Titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("EL TRIGO DE ORO");
        jPanel1.add(Titulo);
        Titulo.setBounds(150, 20, 330, 40);

        areaTelefono.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        areaTelefono.setForeground(new java.awt.Color(0, 0, 0));
        areaTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        areaTelefono.setBorder(null);
        areaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(areaTelefono);
        areaTelefono.setBounds(210, 220, 340, 30);

        jLabel2.setBackground(new java.awt.Color(0, 102, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ACTUALIZAR PROVEEDOR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 60, 250, 40);

        actualizar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("ACTUALIZAR");
        actualizar.setBorder(null);
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar);
        actualizar.setBounds(350, 280, 160, 40);

        textoTelefono.setBackground(new java.awt.Color(0, 102, 255));
        textoTelefono.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textoTelefono.setForeground(new java.awt.Color(0, 0, 0));
        textoTelefono.setText("Teléfono:");
        jPanel1.add(textoTelefono);
        textoTelefono.setBounds(60, 220, 130, 30);

        textoID.setBackground(new java.awt.Color(0, 102, 255));
        textoID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textoID.setForeground(new java.awt.Color(0, 0, 0));
        textoID.setText("ID: ");
        jPanel1.add(textoID);
        textoID.setBounds(60, 120, 30, 30);

        areaID.setEditable(true);
        areaID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        areaID.setForeground(new java.awt.Color(0, 0, 0));
        areaID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        areaID.setBorder(null);
        areaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaIDActionPerformed(evt);
            }
        });
        jPanel1.add(areaID);
        areaID.setBounds(210, 110, 340, 30);

        textoNombre.setBackground(new java.awt.Color(0, 102, 255));
        textoNombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(0, 0, 0));
        textoNombre.setText("Nombre:");
        jPanel1.add(textoNombre);
        textoNombre.setBounds(60, 160, 130, 30);

        areaNombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        areaNombre.setForeground(new java.awt.Color(0, 0, 0));
        areaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        areaNombre.setBorder(null);
        areaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(areaNombre);
        areaNombre.setBounds(210, 160, 340, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoTrigoDeOro (1)_1.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 120, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // Cambio de ventana al menu
        menuProveedores objeto1 = new menuProveedores();
        objeto1.inicial();
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void areaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaTelefonoActionPerformed

    public void actualizarTel(){
        
        Connection conexion = null;

        try {
            conexion = con.getConnection();//se establece la conexion
            ps = conexion.prepareStatement("update trigodeoro.telefonos set telefono=? where id_proveedor=?;");
           // ps.setString(1, area.getText());//El entero hace referencia a la posicion del "?" que se puso en la vinculacion
            ps.setString(1,areaTelefono.getText());
            ps.setInt(2, Integer.valueOf(areaID.getText()));
            
        //Verificar si hay datos
    
            int resultado = ps.executeUpdate();// Ejecuta la modificacion dentro de la DB

            if (resultado > 0) {

                JOptionPane.showMessageDialog(null, "¡Registro modificado correctamente!");
                menuProveedores mp = new menuProveedores();
                mp.inicial();
                dispose();
                //limpiarCajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar el registro", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            conexion.close();//Cierra la conexion

        } catch (Exception ex) {

            System.err.println("Error, " + ex);
        }
    }
    
    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
      
         Connection conexion = null;

        try {
            conexion = con.getConnection();//se establece la conexion
            ps = conexion.prepareStatement("update trigodeoro.proveedores set nombre_proveedor=? where id_proveedor=?");
           // ps.setString(1, area.getText());//El entero hace referencia a la posicion del "?" que se puso en la vinculacion
            ps.setString(1, areaNombre.getText());
            ps.setInt(2, Integer.valueOf(areaID.getText()));
            
        //Verificar si hay datos
            int resultado = ps.executeUpdate();// Ejecuta la modificacion dentro de la DB
            if (resultado > 0) {
                actualizarTel();
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar el registro", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            conexion.close();//Cierra la conexion

        } catch (Exception ex) {

            System.err.println("Error, " + ex);
        }

    }//GEN-LAST:event_actualizarActionPerformed

    private void areaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaNombreActionPerformed

    private void areaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaIDActionPerformed

    public void inicial() {
        this.id = id;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actualizarProveedores().setVisible(true);
            }
        });
    }
    
    public void inicial(int id) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actualizarProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton actualizar;
    public javax.swing.JTextField areaID;
    public javax.swing.JTextField areaNombre;
    public javax.swing.JTextField areaTelefono;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoID;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoTelefono;
    // End of variables declaration//GEN-END:variables
    
}


